# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
  agentpool: 'dockeragent_moises_2'
  prodEnvironmentName: 'production'
  JAVA_LINK: 'https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz'
  JAVA_VERSION: '17.0.5'
  MAVEN_LINK: 'https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz'
  MAVEN_VERSION: '3.8.6'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool: $(agentpool)

    steps:
    - task: CmdLine@2
      displayName: 'Update system, its dependencies and install zip utility.'
      inputs:
        script: |
          apt-get update \
              && apt-get install -y zip tar wget unzip \
              && apt-get autoremove \
              && apt-get clean \
              && rm -rf /var/lib/apt/lists/*
    
    - task: CmdLine@2
      displayName: 'Download and extract JDK 17'
      inputs:
        script: |
          wget -q $(JAVA_LINK) \
              && tar -xf jdk-17_linux-x64_bin.tar.gz -C /opt
        workingDirectory: '$(System.DefaultWorkingDirectory)/src'

    - task: CmdLine@2
      displayName: 'Setting up Java environmental variables'
      inputs:
        script: |
          export JAVA_HOME=/opt/jdk-$(JAVA_VERSION) \
              && export PATH="$JAVA_HOME/bin:$PATH"
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: CmdLine@2
      displayName: 'Download and extract Maven $(MAVEN_VERSION)'
      inputs:
        script: |
          wget -q $(MAVEN_LINK) \
              && tar -xf apache-maven-$(MAVEN_VERSION)-bin.tar.gz -C /opt
        workingDirectory: '$(System.DefaultWorkingDirectory)/src'

    - task: CmdLine@2
      displayName: 'Setting up Maven environmental variables'
      inputs:
        script: |
          export M2_HOME=/opt/apache-maven-$(MAVEN_VERSION) \
              && export PATH="$M2_HOME/bin:$PATH"
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    
    - task: CmdLine@2
      displayName: 'Create project folder'
      inputs:
        script: |
          mkdir pokeshop-backend
        workingDirectory: '$(System.DefaultWorkingDirectory)/src'

    - task: CmdLine@2
      displayName: 'Git clone modules'
      inputs:
        script: |
          git clone -b develop https://github.com/NyoByte/pokeshop-backend-utils \
            && git clone -b develop https://github.com/NyoByte/pokeshop-backend-entity-identidad
        workingDirectory: '$(System.DefaultWorkingDirectory)/src/pokeshop-backend'

    - task: CmdLine@2
      displayName: 'Copy main module'
      inputs:
        script: |
          cp -rf ../Services/Entidad/pokeshop-backend-identidad .
        workingDirectory: '$(System.DefaultWorkingDirectory)/src/pokeshop-backend'

    - task: Maven@4
      displayName: 'Clean install utils module'
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/src/pokeshop-backend/pokeshop-backend-utils/pom.xml'
        options: 'clean install -Dmaven.test.skip=true'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: '/opt/jdk-$(JAVA_VERSION)'
        mavenVersionOption: 'Path'
        mavenDirectory: '/opt/apache-maven-$(MAVEN_VERSION)'
        mavenSetM2Home: true
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Maven@4
      displayName: 'Clean install entity-identidad module'
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/src/pokeshop-backend/pokeshop-backend-entity-identidad/pom.xml'
        options: 'clean install -Dmaven.test.skip=true'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: '/opt/jdk-$(JAVA_VERSION)'
        mavenVersionOption: 'Path'
        mavenDirectory: '/opt/apache-maven-$(MAVEN_VERSION)'
        mavenSetM2Home: true
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Maven@4
      displayName: 'Deploy main module'
      inputs:
        mavenPomFile: '$(System.DefaultWorkingDirectory)/src/pokeshop-backend/pokeshop-backend-identidad/pom.xml'
        options: 'clean package -Dmaven.test.skip=true'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'Path'
        jdkDirectory: '/opt/jdk-$(JAVA_VERSION)'
        mavenVersionOption: 'Path'
        mavenDirectory: '/opt/apache-maven-$(MAVEN_VERSION)'
        mavenSetM2Home: true
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

